CREATE VIEW GEYE_SHOP_FACEDETAIL AS
select IMGSTRINGAWS,DATETIMECRTD,FACE_ID_AWS,IMG_FILE_NAME,SUBSTR(IMGSTRINGAWS,a.L_A_S,a.L_A_C) L_age,SUBSTR(IMGSTRINGAWS,a.H_A_S+10,a.H_A_C) H_age,replace(SUBSTR(IMGSTRINGAWS,a.G_S,a.G_C),"'","")Gender from
(SELECT IMGSTRINGAWS,DATETIMECRTD,FACE_ID_AWS,IMG_FILE_NAME,Locate('AgeRange',IMGSTRINGAWS)+19 L_A_S,
length(SUBSTR(IMGSTRINGAWS, Locate('AgeRange',IMGSTRINGAWS)+19, Locate(", 'High': ",SUBSTR(IMGSTRINGAWS,Locate('AgeRange',IMGSTRINGAWS)+20,length(IMGSTRINGAWS))))) L_A_C, 
Locate('AgeRange',IMGSTRINGAWS)+19+length(SUBSTR(IMGSTRINGAWS, Locate('AgeRange',IMGSTRINGAWS)+19, Locate(", 'High': ",SUBSTR(IMGSTRINGAWS,Locate('AgeRange',IMGSTRINGAWS)+20,length(IMGSTRINGAWS))))) H_A_S,
Locate("}, 'Smile':",SUBSTR(IMGSTRINGAWS,Locate('AgeRange',IMGSTRINGAWS)+19+length(SUBSTR(IMGSTRINGAWS, Locate('AgeRange',IMGSTRINGAWS)+19, Locate(", 'High': ",SUBSTR(IMGSTRINGAWS,Locate('AgeRange',IMGSTRINGAWS)+20,length(IMGSTRINGAWS)))))  
+11,length(IMGSTRINGAWS))) H_A_C,
Locate("'Gender': {'Value': '",IMGSTRINGAWS)+20 G_S,
length(SUBSTR(IMGSTRINGAWS, Locate("'Gender': {'Value': '",IMGSTRINGAWS)+20, Locate("', '",SUBSTR(IMGSTRINGAWS,Locate("'Gender': {'Value': '",IMGSTRINGAWS)+21,length(IMGSTRINGAWS))))) G_C
from  GEYE_SHOPKPR_FACESLOG ) a

>>>>>>>>>>>>>>>>>>>>>***********************>>>>>>>>>>>>>>>>>>>>>>>
CREATE VIEW GEYE_V_FACEDETAIL AS
select idGEYE_CAMERAFACESLOG,DATETIMECREATED,CAMERAID,FACEIDAWS,SUBSTR(FACESTRINGAWS,a.L_A_S,a.L_A_C) L_age,SUBSTR(FACESTRINGAWS,a.H_A_S+10,a.H_A_C) H_age,replace(SUBSTR(FACESTRINGAWS,a.G_S,a.G_C),"'","")Gender from
(SELECT idGEYE_CAMERAFACESLOG,FACESTRINGAWS,DATETIMECREATED,CAMERAID,FACEIDAWS,Locate('AgeRange',FACESTRINGAWS)+19 L_A_S,
length(SUBSTR(FACESTRINGAWS, Locate('AgeRange',FACESTRINGAWS)+19, Locate(", 'High': ",SUBSTR(FACESTRINGAWS,Locate('AgeRange',FACESTRINGAWS)+20,length(FACESTRINGAWS))))) L_A_C, 
Locate('AgeRange',FACESTRINGAWS)+19+length(SUBSTR(FACESTRINGAWS, Locate('AgeRange',FACESTRINGAWS)+19, Locate(", 'High': ",SUBSTR(FACESTRINGAWS,Locate('AgeRange',FACESTRINGAWS)+20,length(FACESTRINGAWS))))) H_A_S,
Locate("}, 'Smile':",SUBSTR(FACESTRINGAWS,Locate('AgeRange',FACESTRINGAWS)+19+length(SUBSTR(FACESTRINGAWS, Locate('AgeRange',FACESTRINGAWS)+19, Locate(", 'High': ",SUBSTR(FACESTRINGAWS,Locate('AgeRange',FACESTRINGAWS)+20,length(FACESTRINGAWS)))))  
+11,length(FACESTRINGAWS))) H_A_C,
Locate("'Gender': {'Value': '",FACESTRINGAWS)+20 G_S,
length(SUBSTR(FACESTRINGAWS, Locate("'Gender': {'Value': '",FACESTRINGAWS)+20, Locate("', '",SUBSTR(FACESTRINGAWS,Locate("'Gender': {'Value': '",FACESTRINGAWS)+21,length(FACESTRINGAWS))))) G_C
from  GEYE_CAMERAFACESLOG ) a


